//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSudentsOIk.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Занятие> Занятие { get; set; }
        public virtual DbSet<Курс> Курс { get; set; }
        public virtual DbSet<Преподаватели> Преподаватели { get; set; }
        public virtual DbSet<Префикс> Префикс { get; set; }
        public virtual DbSet<Пропуски> Пропуски { get; set; }
        public virtual DbSet<Специальность> Специальность { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<СтудентаСтатус> СтудентаСтатус { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
        public virtual DbSet<Фотографии> Фотографии { get; set; }
    }
}
