//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSudentsOIk.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группы()
        {
            this.Студенты = new HashSet<Студенты>();
        }
    
        public int ГруппыId { get; set; }
        public Nullable<int> СпециальностьГруппы { get; set; }
        public Nullable<int> КоличествоСтудентовВГруппе { get; set; }
        public Nullable<int> КоличествоСвободныхМестВГруппе { get; set; }
        public Nullable<int> ПрефиксГруппы { get; set; }
        public Nullable<int> КурсГруппы { get; set; }
        public Nullable<System.DateTime> ДатаФормирования { get; set; }
        public Nullable<System.DateTime> ДатаОкончанияОбучения { get; set; }
        public Nullable<int> КлассныйРуководитель { get; set; }
    
        public virtual Курс Курс { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Префикс Префикс { get; set; }
        public virtual Специальность Специальность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты> Студенты { get; set; }
    }
}
