//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSudentsOIk.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пропуски
    {
        public int ПропускиId { get; set; }
        public Nullable<int> СтудентId { get; set; }
        public Nullable<int> ЗанятияId { get; set; }
    
        public virtual Занятие Занятие { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
