//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSudentsOIk.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фотографии
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Фотографии()
        {
            this.Преподаватели = new HashSet<Преподаватели>();
        }
    
        public int ФотографияId { get; set; }
        public string Фотография { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Преподаватели> Преподаватели { get; set; }
    }
}
